common/models/Questionnaire.php
<?php

namespace common\models;

use Yii;
use yii\db\Query;

/**
 * This is the model class for table "questionnaire".
 *
 * @property integer $id
 * @property integer $survey_id
 * @property string $title
 * @property integer $group
 * @property string $export_name
 * @property string $hide_when_cancelled
 */
class Questionnaire extends \yii\db\ActiveRecord{
    const GROUP_REGISTRIERUNG = -10;
    const GROUP_ERSTERHEBUNG = 0;
    const GROUP_NACHERHEBUNG = 10;

    public static $groupLabels = [
        self::GROUP_REGISTRIERUNG => 'Registrierung',
        self::GROUP_ERSTERHEBUNG => 'Ersterhebung',
        self::GROUP_NACHERHEBUNG => 'Nacherhebung'
    ];

    /**
     * @inheritdoc
     */
    public static function tableName(){
        return 'questionnaire';
    }

    /**
     * @inheritdoc
     */
    public function rules(){
        return [
            [['survey_id', 'title', 'export_name'], 'required'],
            [['survey_id', 'group', 'hide_when_cancelled'], 'integer'],
            [['title', 'export_name'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels(){
        return [
            'id' => 'ID',
            'survey_id' => 'Survey ID',
            'title' => 'Titel',
            'export_name' => 'Name des Tabellenblattes in der Excel-Datei',
            'hide_when_cancelled' => 'Ausblenden, wenn der Proband die Studie abgebrochen hat',
            'group' => 'Gruppe'
        ];
    }

    /**
     * @return Field|null
     */
    public function getFields(){
        return $this->hasMany(Field::className(), ['questionnaire_id' => 'id'])->indexBy('id');
    }
}

backend/controllers/ProbandController.php
<?php

namespace backend\controllers;

use common\models\Proband;
use common\models\Questionnaire;
use common\models\User;
use common\models\Value;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;

/**
 * ProbandController implements the CRUD actions for Proband model.
 */
class ProbandController extends Controller{
    public function behaviors(){
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Proband models.
     * @return mixed
     */
    public function actionIndex(){
        $restrictions = [];
        if(yii::$app->user->getIdentity()->role == User::ROLE_BIOSENS){
            $restrictions['biosens_id'] = [yii::$app->user->id];
        }

        $dataProvider = new ActiveDataProvider([
            'query' => Proband::find()->where($restrictions),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Proband model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id){
        $questionnaires = Questionnaire::findAll(['group' => Questionnaire::GROUP_REGISTRIERUNG]);

        return $this->render('view', [
            'proband' => $this->findModel($id),
            'questionnaires' => $questionnaires
        ]);
    }

    /**
     * Zeigt die Bögen zur Ersterhebung an.
     * @param integer $id
     * @return mixed
     */
    public function actionErsterhebung($id){
        $questionnaires = Questionnaire::findAll(['group' => Questionnaire::GROUP_ERSTERHEBUNG]);

        return $this->render('ersterhebung', [
            'proband' => $this->findModel($id),
            'questionnaires' => $questionnaires
        ]);
    }

    /**
     * Zeigt die Bögen zur Nacherhebung an.
     * @param integer $id
     * @param bool $studie_abgebrochen
     * @return mixed
     */
    public function actionNacherhebung($id, $studie_abgebrochen = null){
        $conditions = [
            'group' => Questionnaire::GROUP_NACHERHEBUNG
        ];
        if($studie_abgebrochen == true){
            $conditions['hide_when_cancelled'] = 0;
        }
        $questionnaires = Questionnaire::find()->where($conditions)->all();

        return $this->render('nacherhebung', [
            'proband' => $this->findModel($id),
            'studie_abgebrochen' => $studie_abgebrochen,
            'questionnaires' => $questionnaires
        ]);
    }

    /**
     * Creates a new Proband model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate(){
        if(time() > strtotime('2016-02-29')){
            return $this->render('noRegistrationAllowed');
        }

        $proband = new Proband();
        $proband->created_at = time();
        $proband->updated_at = time();

        if($proband->load(Yii::$app->request->post())){
            if($proband->validate()){
                $proband->biosens_id = yii::$app->user->id;
                $proband->save(false);
                return $this->redirect(['view', 'id' => $proband->id]);
            }else{
                var_dump($proband->getErrors());
                die();
            }
        }else{
            return $this->render('create', [
                'proband' => $proband,
            ]);
        }
    }

    /**
     * Updates an existing Proband model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id){
        $proband = $this->findModel($id);
        $proband->updated_at = time();

        if($proband->load(Yii::$app->request->post())){
            if($proband->validate()){
                $proband->save(false);
                return $this->redirect(['view', 'id' => $proband->id]);
            }else{
                var_dump($proband->getErrors());
                die();
            }
        }else{
            return $this->render('update', [
                'proband' => $proband,
            ]);
        }
    }

    /**
     * Deletes an existing Proband model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id){
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Zeigt die hochgeladene Einverständniserklärung an.
     * @param integer $id
     * @return mixed
     */
    public function actionEinverstaendniserklaerung($id){
        $upload_einverstaendniserklaerung = $this->findModel($id)->upload_einverstaendniserklaerung;
        if($upload_einverstaendniserklaerung){
            header('Content-type: application/pdf');
            echo $upload_einverstaendniserklaerung;
        }
    }

    /**
     * Zeigt den hochgeladenen Eignungsbogen an.
     * @param integer $id
     * @return mixed
     */
    public function actionEignungsbogen($id){
        $upload_eignungsbogen = $this->findModel($id)->upload_eignungsbogen;
        if($upload_eignungsbogen){
            header('Content-type: application/pdf');
            echo $upload_eignungsbogen;
        }
    }

    /**
     * Zeigt eine hochgeladene Datei an.
     * @param integer $proband_id
     * @param integer $field_id
     * @return mixed
     */
    public function actionViewFile($proband_id, $field_id){
        $value = Value::findOne(['proband_id' => $proband_id, 'field_id' => $field_id]);
        if($value && $value->content){
            $file = $value->content;
            $additionalData = Json::decode($value->additional_data);
            $fileName = $additionalData['fileName'];
            $mimeType = $additionalData['mimeType'];
            header('Content-type: ' . $mimeType);
            header('Content-Disposition: filename="' . $fileName . '"');
            echo $file;
        }
    }

    /**
     * Finds the Proband model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Proband the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id){
        if(($proband = Proband::findOne($id)) !== null){
            return $proband;
        }else{
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * is proband admitted action
     */
    public function actionAdmit($id) {
        $model = $this->findModel($id);
        $model->admitted = 1;
        $model->save();
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * is proband denied
     */
    public function actionDeny($id) {
        $model = $this->findModel($id);
        $model->admitted = 0;
        $model->save();
        return $this->redirect(Yii::$app->request->referrer);
    }
}

backend/controllers/SurveyController.php
<?php

namespace backend\controllers;

use common\models\Questionnaire;
use Yii;
use common\models\Survey;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SurveyController implements the CRUD actions for Survey model.
 */
class SurveyController extends Controller{
    public function behaviors(){
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Survey models.
     * @return mixed
     */
    public function actionIndex(){
        $dataProvider = new ActiveDataProvider([
            'query' => Survey::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Survey model.
     * If creation is successful, the browser will be redirected to the 'update' page.
     * @return mixed
     */
    public function actionCreate(){
        $model = new Survey();

        if($model->load(Yii::$app->request->post()) && $model->save()){
            return $this->redirect(['update', 'id' => $model->id]);
        }else{
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

    /**
     * Updates an existing Survey model.
     * If update is successful, the browser will be redirected to the 'update' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id){
        $model = $this->findModel($id);

        if($model->load(Yii::$app->request->post())){
            $model->save();
        }

        return $this->render('update', [
            'model' => $model,
            'questionnaires' => new ActiveDataProvider([
                'query' => Questionnaire::find()->orderBy('group')->where(['survey_id' => $id]),
                'sort' => false
            ])
        ]);
    }

    /**
     * Deletes an existing Survey model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id){
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Survey model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Survey the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id){
        if(($model = Survey::findOne($id)) !== null){
            return $model;
        }else{
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/questionnaire/_field.php
<?php

use common\models\Field;
use \yii\helpers\Json;

/* @var $value common\models\Value */
/* @var $form yii\widgets\ActiveForm */

$field = $value->field;
$activeField = $form->field($value, "[$field->sorting]content");
$htmlAttributes = [];
// anhängige Felder erstellen
if($field->condition){
    $dependingField = Field::findOne($field->condition);
    $htmlAttributes += [
        'data-dependent-on' => 'Value[' . $dependingField->sorting . '][content]'
    ];
}

$settings = Json::decode($field->settings);

// den Feld-Typ in einen String umwandeln
$fieldClass = new ReflectionClass('common\models\Field');
$constants = $fieldClass->getConstants();

$typeName = null;
foreach($constants as $name => $v){
    if($v == $field->type){
        $typeName = strtolower(str_replace('TYPE_', '', $name));
        break;
    }
}

$this->render('/field/_types/' . $typeName, [
    'value' => $value,
    'field' => $field,
    'activeField' => $activeField,
    'htmlAttributes' => $htmlAttributes,
    'settings' => $settings
]);

$activeField->label($field->label ? $field->label : false);

echo $activeField;

backend/views/questionnaire/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use kartik\grid\GridView;
use kartik\editable\Editable;
use common\models\Field;
use common\models\Questionnaire;
use yii\helpers\Json;

/* @var $this yii\web\View */
/* @var $questionnaire common\models\Questionnaire */
/* @var $fields yii\data\ActiveDataProvider */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="questionnaire-form">

    <?php $form = ActiveForm::begin(); ?>

    <h1><?= Html::encode($this->title) . ' ' . Html::submitButton($questionnaire->isNewRecord ? 'Anlegen' : 'Speichern',
            ['class' => $questionnaire->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?></h1>

    <?= $form->field($questionnaire, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($questionnaire, 'group')->dropDownList(Questionnaire::$groupLabels) ?>

    <?= $form->field($questionnaire, 'export_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($questionnaire, 'hide_when_cancelled')->radioList([0 => 'Nein', 1 => 'Ja']) ?>

    <?php ActiveForm::end(); ?>

    <?php
    $defaultEditableOptions = [
        'preHeader' => '<i class="glyphicon glyphicon-edit"></i> ',
        'header' => 'Bearbeiten',
        'formOptions' => [
            'action' => ['field/update']
        ],
        'pluginEvents' => [
            "editableSuccess" => "function(event, val, form, data){if(data.reload == true) window.location.reload();}",
        ]
    ];

    if(!$questionnaire->isNewRecord){
        echo GridView::widget([
            'dataProvider' => $fields,
            'dataColumnClass' => '\kartik\grid\EditableColumn',
            'layout' => '{toolbar}{items}{toolbar}{pager}',
            'toolbar' => [
                [
                    'content' =>
                        Html::a('<i class="glyphicon glyphicon-plus"></i> Neues Feld anlegen',
                            ['field/create', 'questionnaire_id' => $questionnaire->id],
                            [
                                'title' => 'Neues Feld anlegen',
                                'class' => 'btn btn-success'
                            ])
                ]
            ],
            'columns' => [
                [
                    'attribute' => 'id',
                    'readonly' => true
                ],
                [
                    'attribute' => 'name',
                    'editableOptions' => array_merge_recursive(
                        $defaultEditableOptions,
                        []
                    )
                ],
                [
                    'attribute' => 'label',
                    'editableOptions' => array_merge_recursive(
                        $defaultEditableOptions,
                        [
                            'valueIfNull' => '<em>keine</em>'
                        ]
                    )
                ],
                [
                    'attribute' => 'type',
                    'editableOptions' => array_merge_recursive(
                        $defaultEditableOptions,
                        [
                            'inputType' => Editable::INPUT_DROPDOWN_LIST,
                            'data' => Field::$typeLabels,
                            'displayValueConfig' => Field::$typeLabels
                        ]
                    )
                ],
                [
                    'attribute' => 'default_value',
                    'editableOptions' => array_merge_recursive(
                        $defaultEditableOptions,
                        [
                            'valueIfNull' => '<em>keiner</em>'
                        ]
                    ),
                    // diese Spalte für Überschriften deaktivieren
                    'readonly' => function ($field){
                        switch($field->type){
                            case Field::TYPE_HEADLINE:
                                return true;
                                break;
                            default:
                                return false;
                        }
                    }
                ],
                [
                    'attribute' => 'condition',
                    'editableOptions' => function ($field, $key, $index) use ($questionnaire, $defaultEditableOptions){
                        $fieldsForDisplay =
                            ArrayHelper::map(
                                Field::find()
                                    ->where(['in', 'id', array_keys($questionnaire->fields)])
                                    ->andWhere(['!=', 'id', $field->id])
                                    ->andWhere(['type' => Field::TYPE_YES_NO])
                                    ->orderBy('id')->select('id, name')
                                    ->asArray(true)->all(),
                                'id',
                                function ($field){
                                    return $field['name'];
                                }
                            );

                        return array_merge_recursive(
                            $defaultEditableOptions,
                            [
                                'valueIfNull' => '<em>keinem Feld</em>',
                                'inputType' => Editable::INPUT_DROPDOWN_LIST,
                                'data' => [null => '-'] + $fieldsForDisplay,
                                'displayValueConfig' => [null => '<em>keinem Feld</em>'] + $fieldsForDisplay
                            ]
                        );
                    }
                ],
                [
                    'attribute' => 'settings',
                    'editableOptions' => function ($field, $key, $index) use ($questionnaire, $defaultEditableOptions){
                        // den Feld-Typ in einen String umwandeln
                        $fieldClass = new ReflectionClass('common\models\Field');
                        $constants = $fieldClass->getConstants();

                        $typeName = null;
                        foreach($constants as $name => $v){
                            if($v == $field->type){
                                $typeName = strtolower(str_replace('TYPE_', '', $name));
                                break;
                            }
                        }

                        $settingsPath = '/field/_settings/' . $typeName;

                        $settings = Json::decode($field->settings);

                        return
                            array_merge_recursive(
                                $defaultEditableOptions,
                                [
                                    'valueIfNull' => false,
                                    'inputType' => Editable::INPUT_HIDDEN,
                                    'size' => 'lg',
                                    'displayValue' => $this->render($settingsPath, [
                                        'index' => $index,
                                        'mode' => 'display',
                                        'field' => $field,
                                        'settings' => $settings
                                    ]),
                                    'beforeInput' => function () use ($field, $index, $settingsPath, $settings){
                                        return $this->render($settingsPath, [
                                            'index' => $index,
                                            'mode' => 'edit',
                                            'field' => $field,
                                            'settings' => $settings
                                        ]);
                                    }
                                ]
                            );
                    },
                    // diese Spalte nur für bestimmte Feldtypen aktivieren
                    'readonly' => function ($field){
                        switch($field->type){
                            case Field::TYPE_RADIO_LIST:
                            case Field::TYPE_TABLE:
                            case Field::TYPE_HEADLINE:
                                return false;
                                break;
                            default:
                                return true;
                        }
                    }
                ],
                [
                    'attribute' => 'required',
                    'editableOptions' => array_merge_recursive(
                        $defaultEditableOptions,
                        [
                            'inputType' => Editable::INPUT_RADIO_LIST,
                            'data' => Field::$requiredLabels,
                            'displayValueConfig' => Field::$requiredLabels
                        ]
                    ),
                    // diese Spalte für Überschriften deaktivieren
                    'readonly' => function ($field){
                        switch($field->type){
                            case Field::TYPE_HEADLINE:
                                return true;
                                break;
                            default:
                                return false;
                        }
                    }
                ],
                [
                    'attribute' => 'exportable',
                    'editableOptions' => array_merge_recursive(
                        $defaultEditableOptions,
                        [
                            'inputType' => Editable::INPUT_RADIO_LIST,
                            'data' => Field::$exportableLabels,
                            'displayValueConfig' => Field::$exportableLabels
                        ]
                    )
                ],
                [
                    'class' => '\kartik\grid\ActionColumn',
                    'header' => 'Sortieren',
                    'template' => '{moveTop}{moveUp}{moveDown}{moveBottom} {clone} {delete}',
                    'buttons' => [
                        'moveTop' => function ($url, $field){
                            return Html::a('<i class="glyphicon glyphicon-backward" style="transform: rotate(90deg);"></i>',
                                ['field/move-top', 'id' => $field->id]);
                        },
                        'moveUp' => function ($url, $field){
                            return Html::a('<i class="glyphicon glyphicon-chevron-up"></i>',
                                ['field/move-up', 'id' => $field->id]);
                        },
                        'moveDown' => function ($url, $field){
                            return Html::a('<i class="glyphicon glyphicon-chevron-down"></i>',
                                ['field/move-down', 'id' => $field->id]);
                        },
                        'moveBottom' => function ($url, $field){
                            return Html::a('<i class="glyphicon glyphicon-forward" style="transform: rotate(90deg);"></i>',
                                ['field/move-bottom', 'id' => $field->id]);
                        },
                        'delete' => function ($url, $field){
                            return Html::a('<i class="glyphicon glyphicon-remove text-danger"></i>',
                                ['field/delete', 'id' => $field->id]);
                        },
                        'clone' => function ($url, $field){
                            return Html::a('<i class="glyphicon glyphicon-duplicate"></i>',
                                ['field/create', 'questionnaire_id' => $field->questionnaire_id,
                                    'copy_from_field_id' => $field->id]);
                        }
                    ]
                ]
            ],
            'export' => false,
            'responsive' => true,
            'hover' => true
        ]);
    }
    ?>
</div>

backend/views/questionnaire/create.php
<?php

/* @var $this yii\web\View */
/* @var $questionnaire common\models\Questionnaire */

$survey = common\models\Survey::findOne(['id' => $questionnaire->survey_id]);

$this->title = 'Neuen Fragebogen anlegen';
$this->params['breadcrumbs'][] = ['label' => 'Studie: ' . $survey->title, 'url' => ['survey/update',
    'id' => $questionnaire->survey_id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="questionnaire-create">
    <?= $this->render('_form', [
        'questionnaire' => $questionnaire,
    ]) ?>
</div>

backend/views/questionnaire/export.php
<?php

use \moonland\phpexcel\Excel;

/* @var $this yii\web\View */
/* @var $sheets array */
/* @var $columns array */

Excel::widget([
    'models' => $sheets,
    'isMultipleSheet' => true,
    'mode' => 'export',
    'columns' => $columns
]);

backend/views/questionnaire/fill.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use \common\models\Questionnaire;

/* @var $this yii\web\View */
/* @var $questionnaire common\models\Questionnaire */
/* @var $proband common\models\Proband */
/* @var $values array<common\models\Value> */

$this->title = $proband->first_name . ' ' . $proband->last_name . ': ' . $questionnaire->title;
$this->params['breadcrumbs'][] = ['label' => 'Probanden verwalten', 'url' => ['proband/index']];
$this->params['breadcrumbs'][] = ['label' => $proband->first_name . ' ' . $proband->last_name, 'url' =>
    ['proband/view', 'id' => $proband->id]];

if($questionnaire->group != Questionnaire::GROUP_REGISTRIERUNG){
    $groupLabel = Questionnaire::$groupLabels[$questionnaire->group];
    $this->params['breadcrumbs'][] = ['label' => $groupLabel,
        'url' => ['proband/' . strtolower($groupLabel), 'id' => $proband->id]];
}

$this->params['breadcrumbs'][] = $questionnaire->title;
?>
<div class="questionnaire-fill">

    <?php $form = ActiveForm::begin([
        'options' => [
            'enctype' => 'multipart/form-data'
        ]
    ]); ?>

    <?php
    $saveButton = Html::submitButton('Speichern',
        ['class' => 'btn btn-primary']);
    ?>

    <h1>
        <?= Html::encode($this->title) . ' ' . $saveButton ?>
    </h1>

    <?php
    foreach($values as $value){
        echo $this->render('_field', [
            'value' => $value,
            'form' => $form
        ]);
    }
    ?>

    <?= $saveButton ?>

    <?php ActiveForm::end(); ?>

</div>

backend/views/questionnaire/update.php
<?php

/* @var $this yii\web\View */
/* @var $questionnaire common\models\Questionnaire */
/* @var $fields yii\data\ActiveDataProvider */

$survey = common\models\Survey::findOne(['id' => $questionnaire->survey_id]);

$this->title = $questionnaire->title;
$this->params['breadcrumbs'][] = ['label' => 'Studie: ' . $survey->title, 'url' => ['survey/update',
    'id' => $questionnaire->survey_id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="questionnaire-update">
    <?= $this->render('_form', [
        'questionnaire' => $questionnaire,
        'fields' => $fields
    ]) ?>
</div>