common/models/Survey.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "survey".
 *
 * @property integer $id
 * @property string $title
 * @property integer $start_time
 * @property integer $end_time
 */
class Survey extends \yii\db\ActiveRecord{
    /**
     * @inheritdoc
     */
    public static function tableName(){
        return 'survey';
    }

    /**
     * @inheritdoc
     */
    public function rules(){
        return [
            [['title'], 'required'],
            [['start_time', 'end_time'], 'integer'],
            [['title'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels(){
        return [
            'id' => 'ID',
            'title' => 'Titel',
            'start_time' => 'Startzeit',
            'end_time' => 'Endzeit',
        ];
    }
}

backend/controllers/QuestionnaireController.php
<?php

namespace backend\controllers;

use common\models\Proband;
use Yii;
use common\models\Questionnaire;
use common\models\Field;
use common\models\Value;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;

/**
 * QuestionnaireController implements the CRUD actions for Questionnaire model.
 */
class QuestionnaireController extends Controller{
    public function behaviors(){
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Creates a new Questionnaire model.
     * @param integer $survey_id
     * @param integer $copy_from_questionnaire_id
     * @return mixed
     */
    public function actionCreate($survey_id, $copy_from_questionnaire_id = null){
        $model = new Questionnaire();
        $model->hide_when_cancelled = 0;

        // Duplikat eines Fragebogens erzeugen
        if($copy_from_questionnaire_id != null){
            $questionnaireToClone = Questionnaire::findOne($copy_from_questionnaire_id);
            if($questionnaireToClone){
                $model->attributes = $questionnaireToClone->attributes;
            }
        }

        $model->survey_id = $survey_id;

        if($model->load(Yii::$app->request->post()) && $model->save()){
            if($copy_from_questionnaire_id != null){
                // Felder des Fragebogens duplizieren
                foreach($questionnaireToClone->fields as $fieldToClone){
                    $newField = new Field();
                    $newField->attributes = $fieldToClone->attributes;
                    $newField->questionnaire_id = $model->id;
                    $newField->save();
                }
            }

            return $this->redirect(
                [
                    'update', 'id' => $model->id,
                    'fields' => new ActiveDataProvider([
                        'query' => Field::find()->where(['questionnaire_id' => $model->id])->orderBy('sorting')
                            ->indexBy('id'),
                        'sort' => false
                    ])
                ]
            );
        }else{
            return $this->render('create', [
                'questionnaire' => $model,

            ]);
        }
    }

    /**
     * Updates an existing Questionnaire model.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id){
        $model = $this->findModel($id);

        if($model->load(Yii::$app->request->post())){
            $model->save();
        }

        return $this->render('update', [
            'questionnaire' => $model,
            'fields' => new ActiveDataProvider([
                'query' => Field::find()->where(['questionnaire_id' => $model->id])->orderBy('sorting')->indexBy('id'),
                'sort' => false
            ])
        ]);
    }

    /**
     * Deletes an existing Questionnaire model.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id){
        $model = $this->findModel($id);
        // alle Felder des Fragebogens löschen
        foreach($model->fields as $field){
            $field->delete();
        }
        $model->delete();

        return $this->redirect(['survey/update', 'id' => $model->survey_id]);
    }

    /**
     * Einen Fragebogen ausfüllen.
     * @param integer $id
     * @param integer $proband_id
     * @return mixed
     */
    public function actionFill($id, $proband_id){
        $model = $this->findModel($id);
        $values = [];
        foreach($model->fields as $field){
            $value = Value::findOne(['field_id' => $field->id, 'proband_id' => $proband_id]);
            if(!$value){
                $value = new Value();
                $value->field_id = $field->id;
                $value->proband_id = $proband_id;
                $value->save();
            }
            // die Values werden mit der Sortierungsposition des dazugehörigen Feldes indexiert,
            // damit sie in der richtigen Reihenfolge gerendert werden
            $values[$field->sorting] = $value;
        }
        // Die Values nach der Feld-Position sortieren
        ksort($values);

        if(Value::loadMultiple($values, Yii::$app->request->post()) && Value::validateMultiple($values)){
            foreach($values as $value){
                $value->save(false);
            }

            // Fragebogen als ausgefüllt kennzeichnen
            $proband = Proband::findOne($proband_id);
            $filled_questionnaires = Json::decode($proband->filled_questionnaires);
            if(!in_array($model->id, $filled_questionnaires)) $filled_questionnaires[] = $model->id;
            $proband->filled_questionnaires = Json::encode($filled_questionnaires);
            $proband->save();
        }

        return $this->render('fill', [
            'questionnaire' => $model,
            'proband' => Proband::findOne($proband_id),
            'values' => $values
        ]);
    }

    /**
     * Exportiert eine Gruppe von Fragebögen als Excel-Datei
     * @param $group
     * @return mixed
     */
    public function actionExport($group){
        $questionnaires = Questionnaire::findAll(['group' => $group]);

        // Tabellenblätter
        $sheets = [];
        // Tabellenspalten
        $columns = [];

        foreach($questionnaires as $questionnaire){
            $sheetName = $questionnaire->export_name;

            $values = (new Query())
                ->select('v.proband_id as proband_id, v.content as `content`, f.name as fieldname,'
                    . 'f.type as fieldtype, u.last_name, u.first_name, f.id as fieldId')
                ->from('value v')
                ->join('JOIN', 'field f', 'f.id = v.field_id')
                ->join('JOIN', 'questionnaire q', 'q.id = f.questionnaire_id')
                ->join('JOIN', 'proband p', 'p.id = v.proband_id')
                ->join('JOIN', 'user u', 'u.id = p.biosens_id')
                ->groupBy('v.id')
                ->where(['q.id' => $questionnaire->id, 'f.exportable' => Field::EXPORTABLE_YES])
                ->orderBy('f.sorting')->all();

            // Tabellenzeilen
            $records = [];

            // Spaltendefinitionen für Probandenkennung und Biosens einfügen
            $columns[$sheetName] = [
                'proband_id' => [
                    'header' => 'Proband',
                    'value' => function ($record){
                        return $record['proband_id'];
                    }
                ],
                'biosens' => [
                    'header' => 'Biosens',
                    'value' => function ($record){
                        return $record['biosens'];
                    }
                ]
            ];

            foreach($values as $value){
                $probandId = $value['proband_id'];
                $fieldType = $value['fieldtype'];
                $valueContent = $value['content'];
                $biosens = $value['last_name'] . ', ' . $value['first_name'];

                // Werte für Probandenkennung und Biosens einfügen
                if(!isset($records[$probandId])){
                    $records[$probandId] = [
                        'proband_id' => $probandId,
                        'biosens' => $biosens
                    ];
                }


                // wenn es sich um ein Tabellen-Feld handelt, dann die Werte der Tabellenzellen einfügen
                if($fieldType == Field::TYPE_TABLE || $fieldType == Field::TYPE_BLOOD_PRESSURE_TABLE){
                    $fieldId = $value['fieldId'];
                    // Spaltennamen
                    $columnNames = [];
                    if($fieldType == Field::TYPE_TABLE){
                        $fieldSettings = JSON::decode(Field::findOne($fieldId)->settings);
                        $tableColumns = isset($fieldSettings['columns']) ? $fieldSettings['columns'] : [];

                        foreach($tableColumns as $column){
                            $columnNames[] = $column[1];
                        }
                    }else{
                        $columnNames = ['Tag-%N-Morgens', 'Tag-%N-Mittags', 'Tag-%N-Abends'];
                    }

                    // Feld-Wert in den entsprechenden Datensatz einfügen

                    // Zeilen der Tabelle
                    $rows = JSON::decode($valueContent);
                    // für jede Tabellenzeile werden hier die Spaltennamen eingefügt
                    $fieldNames = [];
                    if(!empty($rows)){
                        foreach($rows as $rowNumber => $row){
                            $fieldNames[$rowNumber] = [];
                            // Spaltenwerte innerhalb der Zeile
                            foreach($row as $n => $colValue){
                                // Platzhalter ersetzen
                                $fieldName = str_replace('%N', $rowNumber + 1, $columnNames[$n]);
                                if($fieldType == Field::TYPE_BLOOD_PRESSURE_TABLE){
                                    $fieldName = $sheetName . ' ' . $fieldName;
                                }

                                $fieldNames[$rowNumber][$n] = $fieldName;
                                $records[$probandId][$fieldName] = $colValue;

                                // Spaltendefinitionen für die Felder einfügen
                                if(!isset($columns[$sheetName][$fieldName])){
                                    $columns[$sheetName][$fieldName] = [
                                        'header' => $fieldName,
                                        'value' => function ($record) use ($fieldName){
                                            return isset($record[$fieldName]) ? $record[$fieldName] : '';

backend/controllers/SurveyController.php
<?php

namespace backend\controllers;

use common\models\Questionnaire;
use Yii;
use common\models\Survey;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SurveyController implements the CRUD actions for Survey model.
 */
class SurveyController extends Controller{
    public function behaviors(){
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Survey models.
     * @return mixed
     */
    public function actionIndex(){
        $dataProvider = new ActiveDataProvider([
            'query' => Survey::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Survey model.
     * If creation is successful, the browser will be redirected to the 'update' page.
     * @return mixed
     */
    public function actionCreate(){
        $model = new Survey();

        if($model->load(Yii::$app->request->post()) && $model->save()){
            return $this->redirect(['update', 'id' => $model->id]);
        }else{
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

    /**
     * Updates an existing Survey model.
     * If update is successful, the browser will be redirected to the 'update' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id){
        $model = $this->findModel($id);

        if($model->load(Yii::$app->request->post())){
            $model->save();
        }

        return $this->render('update', [
            'model' => $model,
            'questionnaires' => new ActiveDataProvider([
                'query' => Questionnaire::find()->orderBy('group')->where(['survey_id' => $id]),
                'sort' => false
            ])
        ]);
    }

    /**
     * Deletes an existing Survey model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id){
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Survey model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Survey the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id){
        if(($model = Survey::findOne($id)) !== null){
            return $model;
        }else{
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/survey/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model common\models\Survey */
/* @var $form yii\widgets\ActiveForm */
/* @var $questionaires yii\data\ActiveDataProvider */
?>

<div class="survey-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'start_time')->textInput() ?>

    <?= $form->field($model, 'end_time')->textInput() ?>

    <div>
        <h2>Fragebögen:</h2>
        <?= Html::a('Neuen Fragebogen anlegen', ['questionnaire/create', 'survey_id' => $model->id],
            ['class' => 'btn btn-primary']) ?>
        <?= GridView::widget([
            'dataProvider' => $questionnaires,
            'columns' => [
                'title',
                [
                    'attribute' => 'group',
                    'content' => function($questionnaire){
                        return \common\models\Questionnaire::$groupLabels[$questionnaire->group];
                    }
                ],

                [
                    'class' => 'yii\grid\ActionColumn',
                    'controller' => 'questionnaire',
                    'template' => '{update} {clone} {delete}',
                    'buttons' => [
                        'clone' => function ($url, $questionnaire) use ($model){
                            return Html::a('<i class="glyphicon glyphicon-duplicate"></i>',
                                ['questionnaire/create', 'survey_id' => $model->id,
                                    'copy_from_questionnaire_id' => $questionnaire->id]);
                        }
                    ]
                ],
            ],
        ]) ?>
    </div>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/survey/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Survey */

$this->title = 'Create Survey';
$this->params['breadcrumbs'][] = ['label' => 'Surveys', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="survey-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/survey/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Surveys';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="survey-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Neue Studie anlegen', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'title',
            'start_time:datetime',
            'end_time:datetime',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}'
            ],
        ],
    ]); ?>

</div>

backend/views/survey/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Survey */
/* @var $questionaires yii\data\ActiveDataProvider */

$this->title = 'Studie: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Studien', 'url' => ['index']];
$this->params['breadcrumbs'][] = $model->title;
?>
<div class="survey-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'questionnaires' => $questionnaires
    ]) ?>

</div>