backend/controllers/ProbandController.php
<?php

namespace backend\controllers;

use common\models\Proband;
use common\models\Questionnaire;
use common\models\User;
use common\models\Value;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;

/**
 * ProbandController implements the CRUD actions for Proband model.
 */
class ProbandController extends Controller{
    public function behaviors(){
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Proband models.
     * @return mixed
     */
    public function actionIndex(){
        $restrictions = [];
        if(yii::$app->user->getIdentity()->role == User::ROLE_BIOSENS){
            $restrictions['biosens_id'] = [yii::$app->user->id];
        }

        $dataProvider = new ActiveDataProvider([
            'query' => Proband::find()->where($restrictions),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Proband model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id){
        $questionnaires = Questionnaire::findAll(['group' => Questionnaire::GROUP_REGISTRIERUNG]);

        return $this->render('view', [
            'proband' => $this->findModel($id),
            'questionnaires' => $questionnaires
        ]);
    }

    /**
     * Zeigt die Bögen zur Ersterhebung an.
     * @param integer $id
     * @return mixed
     */
    public function actionErsterhebung($id){
        $questionnaires = Questionnaire::findAll(['group' => Questionnaire::GROUP_ERSTERHEBUNG]);

        return $this->render('ersterhebung', [
            'proband' => $this->findModel($id),
            'questionnaires' => $questionnaires
        ]);
    }

    /**
     * Zeigt die Bögen zur Nacherhebung an.
     * @param integer $id
     * @param bool $studie_abgebrochen
     * @return mixed
     */
    public function actionNacherhebung($id, $studie_abgebrochen = null){
        $conditions = [
            'group' => Questionnaire::GROUP_NACHERHEBUNG
        ];
        if($studie_abgebrochen == true){
            $conditions['hide_when_cancelled'] = 0;
        }
        $questionnaires = Questionnaire::find()->where($conditions)->all();

        return $this->render('nacherhebung', [
            'proband' => $this->findModel($id),
            'studie_abgebrochen' => $studie_abgebrochen,
            'questionnaires' => $questionnaires
        ]);
    }

    /**
     * Creates a new Proband model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate(){
        if(time() > strtotime('2016-02-29')){
            return $this->render('noRegistrationAllowed');
        }

        $proband = new Proband();
        $proband->created_at = time();
        $proband->updated_at = time();

        if($proband->load(Yii::$app->request->post())){
            if($proband->validate()){
                $proband->biosens_id = yii::$app->user->id;
                $proband->save(false);
                return $this->redirect(['view', 'id' => $proband->id]);
            }else{
                var_dump($proband->getErrors());
                die();
            }
        }else{
            return $this->render('create', [
                'proband' => $proband,
            ]);
        }
    }

    /**
     * Updates an existing Proband model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id){
        $proband = $this->findModel($id);
        $proband->updated_at = time();

        if($proband->load(Yii::$app->request->post())){
            if($proband->validate()){
                $proband->save(false);
                return $this->redirect(['view', 'id' => $proband->id]);
            }else{
                var_dump($proband->getErrors());
                die();
            }
        }else{
            return $this->render('update', [
                'proband' => $proband,
            ]);
        }
    }

    /**
     * Deletes an existing Proband model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id){
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Zeigt die hochgeladene Einverständniserklärung an.
     * @param integer $id
     * @return mixed
     */
    public function actionEinverstaendniserklaerung($id){
        $upload_einverstaendniserklaerung = $this->findModel($id)->upload_einverstaendniserklaerung;
        if($upload_einverstaendniserklaerung){
            header('Content-type: application/pdf');
            echo $upload_einverstaendniserklaerung;
        }
    }

    /**
     * Zeigt den hochgeladenen Eignungsbogen an.
     * @param integer $id
     * @return mixed
     */
    public function actionEignungsbogen($id){
        $upload_eignungsbogen = $this->findModel($id)->upload_eignungsbogen;
        if($upload_eignungsbogen){
            header('Content-type: application/pdf');
            echo $upload_eignungsbogen;
        }
    }

    /**
     * Zeigt eine hochgeladene Datei an.
     * @param integer $proband_id
     * @param integer $field_id
     * @return mixed
     */
    public function actionViewFile($proband_id, $field_id){
        $value = Value::findOne(['proband_id' => $proband_id, 'field_id' => $field_id]);
        if($value && $value->content){
            $file = $value->content;
            $additionalData = Json::decode($value->additional_data);
            $fileName = $additionalData['fileName'];
            $mimeType = $additionalData['mimeType'];
            header('Content-type: ' . $mimeType);
            header('Content-Disposition: filename="' . $fileName . '"');
            echo $file;
        }
    }

    /**
     * Finds the Proband model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Proband the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id){
        if(($proband = Proband::findOne($id)) !== null){
            return $proband;
        }else{
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * is proband admitted action
     */
    public function actionAdmit($id) {
        $model = $this->findModel($id);
        $model->admitted = 1;
        $model->save();
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * is proband denied
     */
    public function actionDeny($id) {
        $model = $this->findModel($id);
        $model->admitted = 0;
        $model->save();
        return $this->redirect(Yii::$app->request->referrer);
    }
}

backend/controllers/QuestionnaireController.php
<?php

namespace backend\controllers;

use common\models\Proband;
use Yii;
use common\models\Questionnaire;
use common\models\Field;
use common\models\Value;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;

/**
 * QuestionnaireController implements the CRUD actions for Questionnaire model.
 */
class QuestionnaireController extends Controller{
    public function behaviors(){
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Creates a new Questionnaire model.
     * @param integer $survey_id
     * @param integer $copy_from_questionnaire_id
     * @return mixed
     */
    public function actionCreate($survey_id, $copy_from_questionnaire_id = null){
        $model = new Questionnaire();
        $model->hide_when_cancelled = 0;

        // Duplikat eines Fragebogens erzeugen
        if($copy_from_questionnaire_id != null){
            $questionnaireToClone = Questionnaire::findOne($copy_from_questionnaire_id);
            if($questionnaireToClone){
                $model->attributes = $questionnaireToClone->attributes;
            }
        }

        $model->survey_id = $survey_id;

        if($model->load(Yii::$app->request->post()) && $model->save()){
            if($copy_from_questionnaire_id != null){
                // Felder des Fragebogens duplizieren
                foreach($questionnaireToClone->fields as $fieldToClone){
                    $newField = new Field();
                    $newField->attributes = $fieldToClone->attributes;
                    $newField->questionnaire_id = $model->id;
                    $newField->save();
                }
            }

            return $this->redirect(
                [
                    'update', 'id' => $model->id,
                    'fields' => new ActiveDataProvider([
                        'query' => Field::find()->where(['questionnaire_id' => $model->id])->orderBy('sorting')
                            ->indexBy('id'),
                        'sort' => false
                    ])
                ]
            );
        }else{
            return $this->render('create', [
                'questionnaire' => $model,

            ]);
        }
    }

    /**
     * Updates an existing Questionnaire model.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id){
        $model = $this->findModel($id);

        if($model->load(Yii::$app->request->post())){
            $model->save();
        }

        return $this->render('update', [
            'questionnaire' => $model,
            'fields' => new ActiveDataProvider([
                'query' => Field::find()->where(['questionnaire_id' => $model->id])->orderBy('sorting')->indexBy('id'),
                'sort' => false
            ])
        ]);
    }

    /**
     * Deletes an existing Questionnaire model.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id){
        $model = $this->findModel($id);
        // alle Felder des Fragebogens löschen
        foreach($model->fields as $field){
            $field->delete();
        }
        $model->delete();

        return $this->redirect(['survey/update', 'id' => $model->survey_id]);
    }

    /**
     * Einen Fragebogen ausfüllen.
     * @param integer $id
     * @param integer $proband_id
     * @return mixed
     */
    public function actionFill($id, $proband_id){
        $model = $this->findModel($id);
        $values = [];
        foreach($model->fields as $field){
            $value = Value::findOne(['field_id' => $field->id, 'proband_id' => $proband_id]);
            if(!$value){
                $value = new Value();
                $value->field_id = $field->id;
                $value->proband_id = $proband_id;
                $value->save();
            }
            // die Values werden mit der Sortierungsposition des dazugehörigen Feldes indexiert,
            // damit sie in der richtigen Reihenfolge gerendert werden
            $values[$field->sorting] = $value;
        }
        // Die Values nach der Feld-Position sortieren
        ksort($values);

        if(Value::loadMultiple($values, Yii::$app->request->post()) && Value::validateMultiple($values)){
            foreach($values as $value){
                $value->save(false);
            }

            // Fragebogen als ausgefüllt kennzeichnen
            $proband = Proband::findOne($proband_id);
            $filled_questionnaires = Json::decode($proband->filled_questionnaires);
            if(!in_array($model->id, $filled_questionnaires)) $filled_questionnaires[] = $model->id;
            $proband->filled_questionnaires = Json::encode($filled_questionnaires);
            $proband->save();
        }

        return $this->render('fill', [
            'questionnaire' => $model,
            'proband' => Proband::findOne($proband_id),
            'values' => $values
        ]);
    }

    /**
     * Exportiert eine Gruppe von Fragebögen als Excel-Datei
     * @param $group
     * @return mixed
     */
    public function actionExport($group){
        $questionnaires = Questionnaire::findAll(['group' => $group]);

        // Tabellenblätter
        $sheets = [];
        // Tabellenspalten
        $columns = [];

        foreach($questionnaires as $questionnaire){
            $sheetName = $questionnaire->export_name;

            $values = (new Query())
                ->select('v.proband_id as proband_id, v.content as `content`, f.name as fieldname,'
                    . 'f.type as fieldtype, u.last_name, u.first_name, f.id as fieldId')
                ->from('value v')
                ->join('JOIN', 'field f', 'f.id = v.field_id')
                ->join('JOIN', 'questionnaire q', 'q.id = f.questionnaire_id')
                ->join('JOIN', 'proband p', 'p.id = v.proband_id')
                ->join('JOIN', 'user u', 'u.id = p.biosens_id')
                ->groupBy('v.id')
                ->where(['q.id' => $questionnaire->id, 'f.exportable' => Field::EXPORTABLE_YES])
                ->orderBy('f.sorting')->all();

            // Tabellenzeilen
            $records = [];

            // Spaltendefinitionen für Probandenkennung und Biosens einfügen
            $columns[$sheetName] = [
                'proband_id' => [
                    'header' => 'Proband',
                    'value' => function ($record){
                        return $record['proband_id'];
                    }
                ],
                'biosens' => [
                    'header' => 'Biosens',
                    'value' => function ($record){
                        return $record['biosens'];
                    }
                ]
            ];

            foreach($values as $value){
                $probandId = $value['proband_id'];
                $fieldType = $value['fieldtype'];
                $valueContent = $value['content'];
                $biosens = $value['last_name'] . ', ' . $value['first_name'];

                // Werte für Probandenkennung und Biosens einfügen
                if(!isset($records[$probandId])){
                    $records[$probandId] = [
                        'proband_id' => $probandId,
                        'biosens' => $biosens
                    ];
                }


                // wenn es sich um ein Tabellen-Feld handelt, dann die Werte der Tabellenzellen einfügen
                if($fieldType == Field::TYPE_TABLE || $fieldType == Field::TYPE_BLOOD_PRESSURE_TABLE){
                    $fieldId = $value['fieldId'];
                    // Spaltennamen
                    $columnNames = [];
                    if($fieldType == Field::TYPE_TABLE){
                        $fieldSettings = JSON::decode(Field::findOne($fieldId)->settings);
                        $tableColumns = isset($fieldSettings['columns']) ? $fieldSettings['columns'] : [];

                        foreach($tableColumns as $column){
                            $columnNames[] = $column[1];
                        }
                    }else{
                        $columnNames = ['Tag-%N-Morgens', 'Tag-%N-Mittags', 'Tag-%N-Abends'];
                    }

                    // Feld-Wert in den entsprechenden Datensatz einfügen

                    // Zeilen der Tabelle
                    $rows = JSON::decode($valueContent);
                    // für jede Tabellenzeile werden hier die Spaltennamen eingefügt
                    $fieldNames = [];
                    if(!empty($rows)){
                        foreach($rows as $rowNumber => $row){
                            $fieldNames[$rowNumber] = [];
                            // Spaltenwerte innerhalb der Zeile
                            foreach($row as $n => $colValue){
                                // Platzhalter ersetzen
                                $fieldName = str_replace('%N', $rowNumber + 1, $columnNames[$n]);
                                if($fieldType == Field::TYPE_BLOOD_PRESSURE_TABLE){
                                    $fieldName = $sheetName . ' ' . $fieldName;
                                }

                                $fieldNames[$rowNumber][$n] = $fieldName;
                                $records[$probandId][$fieldName] = $colValue;

                                // Spaltendefinitionen für die Felder einfügen
                                if(!isset($columns[$sheetName][$fieldName])){
                                    $columns[$sheetName][$fieldName] = [
                                        'header' => $fieldName,
                                        'value' => function ($record) use ($fieldName){
                                            return isset($record[$fieldName]) ? $record[$fieldName] : '';

backend/views/proband/_buttons_boegen.php
<?php
use yii\helpers\Html;
use yii\helpers\Json;

/* @var $proband common\models\Proband */
/* @var $questionnaires array<common\models\Questionnaire> */

$filled = [];
$notFilled = [];

foreach($questionnaires as $questionnaire){
    $button = Html::a($questionnaire->title, ['questionnaire/fill', 'proband_id' => $proband->id,
        'id' => $questionnaire->id], ['class' => 'btn btn-primary']);

    $filled_questionnaires = Json::decode($proband->filled_questionnaires);
    if($filled_questionnaires == null){
        $filled_questionnaires = [];
    }
    if(in_array($questionnaire->id, $filled_questionnaires)){
        $filled[] = $button;
    }else{
        $notFilled[] = $button;
    }
}

?>
<div class=" row">
    <div class="col-md-6">
        <?php
        if(!empty($notFilled)){
            echo '<h3>Noch nicht eingegeben:</h3>';
            foreach($notFilled as $button){
                echo $button;
            }
        }
        ?>
    </div>
    <div class="col-md-6">
        <?php
        if(!empty($filled)){
            echo '<h3>Bereits eingegeben:</h3>';
            foreach($filled as $button){
                echo $button;
            }
        }
        ?>
    </div>
</div>

backend/views/proband/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $proband common\models\Proband */
/* @var $form yii\widgets\ActiveForm */

if($proband->isNewRecord){
    $this->title = 'Registrierung eines Probanden in der BioMeZ-Studie "Biomeditation bei Bluthochdruck" 2015/2016';
    $this->params['breadcrumbs'][] = 'Proband registieren';
}else{
    $this->title = 'Probandendaten bearbeiten';
    $this->params['breadcrumbs'][] = $this->title;
}
?>

<div class="proband-form">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    if($proband->isNewRecord){
        ?>
        <script type="text/javascript">
            $(function(){
                var $mandatoryQuestions = $('[name^=mandatory-question-]');
                $mandatoryQuestions.change(function(){
                    if($('[name^=mandatory-question-1]:checked').prop('value') == 1 &&
                        $('[name^=mandatory-question-2]:checked').prop('value') == 1
                    ){
                        $('form').removeClass('hidden');
                        $('#mandatory-message').hide();
                    }else{
                        $('form').addClass('hidden');
                        $('#mandatory-message').show();
                    }
                });
            });
        </script>

        <div class="form-group">
            <label>
                Hat ein Arzt bei Deinem Probanden einen <strong>Bluthochdruck</strong> diagnostiziert?
            </label>
            <input type="radio" name="mandatory-question-1" value="0" checked="checked"/> nein
            <input type="radio" name="mandatory-question-1" value="1"/> ja
        </div>

        <div class="form-group">
            <label>
                Hat oder hatte Dein Proband (vor Einnahme blutdrucksenkender Medikamente) durchschnittlich systolische
                Blutdruckwerte von über 160 mm Hg?
            </label>
            <input type="radio" name="mandatory-question-2" value="0" checked="checked"/> nein
            <input type="radio" name="mandatory-question-2" value="1"/> ja
        </div>

        <div id="mandatory-message" class="alert alert-danger">
            Nur wenn beide Fragen mit "ja" beantwortet werden, darf die Registrierung genehmigt werden.<br/>
            Voraussetzung für die Teilnahme an der Studie ist, dass bei Deinem Probanden ein sogenannter mittlerer oder
            schwerer Blutdruck vorliegt, d. h. mit Blutdruckwerten von systolisch > 160 oder > 180 mm Hg.
        </div>
    <?php } ?>

    <?php $form = ActiveForm::begin([
        'options' => [
            'class' => $proband->isNewRecord ? 'hidden' : '',
            'enctype' => 'multipart/form-data'
        ]
    ]); ?>

    <?= $form->field($proband, 'title')->textInput() ?>
    <?= $form->field($proband, 'last_name')->textInput() ?>
    <?= $form->field($proband, 'first_name')->textInput() ?>
    <?= $form->field($proband, 'date_of_birth')->widget(\yii\jui\DatePicker::className(), [
        'options' => ['class' => 'form-control'],
        'model' => $proband,
        'attribute' => 'date_of_birth',
        'language' => 'de',
        'dateFormat' => 'dd.MM.yyyy',
    ]) ?>
    <?= $form->field($proband, 'sex')->radioList([\common\models\User::SEX_MALE => 'männlich',
        \common\models\User::SEX_FEMALE => 'weiblich']) ?>
    <?= $form->field($proband, 'street')->textInput() ?>
    <?= $form->field($proband, 'street_number')->textInput() ?>
    <?= $form->field($proband, 'zip_code')->textInput() ?>
    <?= $form->field($proband, 'city')->textInput() ?>
    <?= $form->field($proband, 'country')->widget(\yii\jui\AutoComplete::classname(), [
        'options' => ['class' => 'form-control'],
        'clientOptions' => [
            'source' => ['Deutschland', 'Österreich']
        ],
    ]) ?>
    <?= $form->field($proband, 'phone_prefix') ?>
    <?= $form->field($proband, 'phone_number') ?>
    <?= $form->field($proband, 'email')->textInput() ?>
    <?= $form->field($proband, 'month_and_year_of_diagnosis')->textInput() ?>

    <h2>Angaben zu etwaigen Biomeditationssitzungen des Probanden</h2>

    <?= $form->field($proband, 'has_yet_attended_a_treatment')->radioList([0 => 'nein', 1 => 'ja']) ?>
    <?= $form->field($proband, 'time_since_last_treatment')->textInput([
        'data-dependent-on' => 'Proband[has_yet_attended_a_treatment]'
    ])->label('Wann hatte Dein Proband die letzte Sitzung?<br />' .
        'Die letzte Sitzung hatte mein Proband vor ...<br />' .
        'Bsp.: 14 Tagen oder 2 Monaten') ?>
    <?= $form->field($proband, 'count_of_treatments')->textInput([
        'data-dependent-on' => 'Proband[has_yet_attended_a_treatment]'
    ])->label('Wieviele Sitzungen hatte Dein Proband in etwa <em>insgesamt</em>?') ?>

    <h2>Anmeldebögen hochladen</h2>
    <?= $form->field($proband, 'upload_einverstaendniserklaerung')->fileInput() ?>
    <?= $form->field($proband, 'upload_eignungsbogen')->fileInput() ?>
    <?= $form->field($proband, 'how_took_notice') ?>

    <div class="form-group">
        <?= Html::submitButton('Speichern',
            ['class' => $proband->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/proband/create.php
<?php

use yii\helpers\Html;
use common\models\User;


/* @var $this yii\web\View */
/* @var $proband common\models\Proband */

$this->title = 'Benutzer anlegen';
$this->params['breadcrumbs'][] = ['label' => 'Probanden', 'url' => ['index']];

?>
<div class="user-create">
    <?php
        echo $this->render('_form', [
            'proband' => $proband
        ]);
    ?>
</div>

backend/views/proband/delete.php
<?php
/* @var $this yii\web\View */
?>
<h1>proband/delete</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

backend/views/proband/ersterhebung.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $proband common\models\Proband */
/* @var $questionnaires array<common\models\Questionnaire> */

$this->title = $proband->first_name . ' ' . $proband->last_name . ': Ersterhebung';
$this->params['breadcrumbs'][] = ['label' => 'Probanden verwalten', 'url' => ['proband/index']];
$this->params['breadcrumbs'][] = ['label' => $proband->first_name . ' ' . $proband->last_name, 'url' =>
    ['proband/view', 'id' => $proband->id]];
$this->params['breadcrumbs'][] = 'Ersterhebung';
?>

<div class="proband-ersterhebung">
    <div class="panel panel-default">
        <div class="panel-heading"><h1><?= Html::encode($this->title) ?></h1></div>
        <div class="panel-body">
            <p>
                <?= $this->render('_buttons_boegen', [
                    'proband' => $proband,
                    'questionnaires' => $questionnaires
                ]) ?>
            </p>
        </div>
    </div>
</div>

backend/views/proband/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use \common\models\User;
use \common\models\Questionnaire;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Probanden verwalten';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="proband-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Proband registrieren', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Registrierungsdaten exportieren', ['/questionnaire/export',
            'group' => Questionnaire::GROUP_REGISTRIERUNG], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Ersterhebung exportieren', ['/questionnaire/export', 'group' => Questionnaire::GROUP_ERSTERHEBUNG],
            ['class' => 'btn btn-success']) ?>
        <?= Html::a('Nacherhebung exportieren', ['/questionnaire/export', 'group' => Questionnaire::GROUP_NACHERHEBUNG],
            ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            'title',
            'first_name',
            'last_name',
            'email:email',
            [
                'attribute' => 'sex',
                'content' => function ($model){
                    return $model->sex == User::SEX_MALE ? 'männlich' : 'weiblich';
                }
            ],
            [
                'attribute' => 'created_at',
                'content' => function ($model){
                    return date('d.m.y', $model->created_at);
                }
            ],
            'street',
            'street_number',
            'zip_code',
            'city',
            'country',
            [
                'attribute' => 'date_of_birth',
                'content' => function ($model){
                    return date('d.m.y', $model->date_of_birth);
                }
            ],

            [
                'content' => function ($model) {
                    if($model->admitted === NULL) {
                        return Html::a('Zulassen', ['admit', 'id' => $model->id], ['class' => 'btn btn-success']) .
                        Html::a('Ablehnen', ['deny', 'id' => $model->id], ['class' => 'btn btn-danger']);
                    } else {
                        if($model->admitted == 1) {
                            return 'zugelassen ' . Html::a('Ablehnen', ['deny', 'id' => $model->id],
                                ['class' => 'btn btn-danger']);
                        } else {
                            return 'abgelehnt ' . Html::a('Zulassen', ['admit', 'id' => $model->id],
                                ['class' => 'btn btn-success']);
                        }
                    }
                }
            ],

            [
                'content' => function ($model){
                    return Html::a('Ersterhebung', ['ersterhebung', 'id' => $model->id],
                        ['class' => 'btn btn-primary']);
                }
            ],
            [
                'content' => function ($model){
                    return Html::a('Nacherhebung', ['nacherhebung', 'id' => $model->id],
                        ['class' => 'btn btn-primary']);
                }
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

backend/views/proband/nacherhebung.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $proband common\models\Proband */
/* @var $studie_abgebrochen boolean */
/* @var $questionnaires array<common\models\Questionnaire> */

$this->title = $proband->first_name . ' ' . $proband->last_name . ': Nacherhebung';
$this->params['breadcrumbs'][] = ['label' => 'Probanden verwalten', 'url' => ['proband/index']];
$this->params['breadcrumbs'][] = ['label' => $proband->first_name . ' ' . $proband->last_name, 'url' =>
    ['proband/view', 'id' => $proband->id]];
$this->params['breadcrumbs'][] = 'Nacherhebung';
?>

<div class="proband-nacherhebung">
    <div class="panel panel-default">
        <div class="panel-heading"><h1><?= Html::encode($this->title) ?></h1></div>
        <div class="panel-body">
            <?php
            if($studie_abgebrochen === null){
                ?>
                <h2>Hat der Proband die Studie abgebrochen?
                    <?= Html::a('Nein', ['nacherhebung', 'id' => $proband->id, 'studie_abgebrochen' => false],
                        ['class' => 'btn btn-success']) ?>
                    <?= Html::a('Ja', ['nacherhebung', 'id' => $proband->id, 'studie_abgebrochen' => true],
                        ['class' => 'btn btn-danger']) ?>
                </h2>
                <?php
            }else{
                echo $this->render('_buttons_boegen', [
                    'proband' => $proband,
                    'questionnaires' => $questionnaires
                ]);
            }
            ?>
        </div>
    </div>
</div>

backend/views/proband/noRegistrationAllowed.php
<div class="alert alert-warning" role="alert">
    Es können keine Probanden mehr registriert werden.
</div>

backend/views/proband/update.php
<?php

/* @var $this yii\web\View */
/* @var $proband common\models\Proband */

$this->title = $proband->first_name . ' ' . $proband->last_name;
$this->params['breadcrumbs'][] = ['label' => 'Probanden verwalten', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $proband->first_name . ' ' . $proband->last_name, 'url' => ['view', 'id' => $proband->id]];
?>
<div class="proband-update">
    <?php
        echo $this->render('_form', [
            'proband' => $proband,
        ]);
    ?>

</div>